### ISSUE TITLE
Is it possible to convert all px values ​​of the entire buffer with one click?

### ISSUE THREAD

**Issue by kola-web** [jsongerber/nvim-px-to-rem#1]

**Comment by jsongerber** [comment]
I don't want to implement this feature because I don't think this is a good practice to use rem everywhere.
But if you would like to convert an entire file you can use
`:g/^ /PxToRemLine`
Or create a keymap:
`vim.keymap.set('n', '<leader>pxf', '<cmd>g/^ /PxToRemLine<cr>' { noremap = true, desc = 'Convert pixels to rem in the entire file'})`
I didn't test but this should work

**Comment by kola-web** [comment]
thank you for your reply
